---
title: "make.phyllo.sampling.map"
format: html
toc: true
toc-title: Document Contents
number-sections: true
embed-resources: true
---

## read in data and load packages
```{r}
#| output: false
library(vcfR) #v1.14.0
library(ggplot2) #v3.4.4
library(maps) #v3.4.1.1
library(sf) #v1.0-14
library(RColorBrewer) #v1.1-3
library(khroma)

#read in sampling info
samps<-read.csv("~/Desktop/phyllo.wgs/phyllo.wgs.sampling.for.plotting.csv")
```

## prepare datframes for plotting
```{r}
#split df by locality
spec.dfs<-split(samps, samps$locality)

#init sampling.df which will be a df of samples grouped by unique lat/long
sampling.df<-data.frame(NULL)
for (i in names(spec.dfs)){
  samps<-spec.dfs[[i]] %>% dplyr::group_by(lat, long) %>% dplyr::summarize(count=dplyr::n())
  df<-cbind(rep(i, times=nrow(samps)), samps)
  sampling.df<-as.data.frame(rbind(sampling.df, df))
}

#fix colnames
colnames(sampling.df)<-c("species","lat","long","count")
#reorder factors
#sampling.df$species <- factor(sampling.df$species, levels = c("margarethae","dispar","gentianus","malaitae","meeki","nigromaxilla","collectoris","sacerdotis","solitarius","mulcatus"))
```


## plot all of the nmel species together
We will use Paul Tol's [muted qualitative color scheme](https://personal.sron.nl/~pault/data/colourschemes.pdf), which is a color-blind friendly diverging palette, plus the addition of white, for the outgroup margarethae.
```{r}
#make map#
pac<-map_data("world")
#get scheme
muted <- color("muted")
plot_scheme(muted(5), colours = TRUE, names = TRUE, size = 0.9)
muted(5)
# plot all samples
ggplot()+
  geom_polygon(data = pac, aes(x=long, y = lat, group = group), fill="lightgrey", col="black", cex=.1)+
  coord_sf(xlim = c(143, 162), ylim = c(-12, -2)) + 
  geom_point(data = sampling.df, aes(x = long, y = lat, fill=species, size=count), pch=21, color="black", alpha =.8, show.legend=TRUE) +
  theme_classic()+
  scale_fill_manual(values=c("#CC6677","#332288","#DDCC77","#117733","#88CCEE","#DDDDDD"))+
  scale_size_continuous(range = c(3,6))+
  guides(fill = guide_legend(override.aes = list(size = 6), order=1, label.theme = element_text(face = "italic")),
         size = guide_legend(order = 2))+
  theme(legend.position = NULL)

# plot all samples
ggplot()+
  geom_polygon(data = pac, aes(x=long, y = lat, group = group), fill="lightgrey", col="black", cex=.1)+
  coord_sf(xlim = c(143, 162), ylim = c(-12, -2)) + 
  #geom_point(data = sampling.df, aes(x = long, y = lat, fill=species, size=count), pch=21, color="black", alpha =.8, show.legend=TRUE) +
  theme_classic()+
  #scale_fill_manual(values=c("#CC6677","#332288","#DDCC77","#117733","#88CCEE","#DDDDDD"))+
  scale_size_continuous(range = c(3,6))+
  guides(fill = guide_legend(override.aes = list(size = 6), order=1, label.theme = element_text(face = "italic")),
         size = guide_legend(order = 2))+
  theme(legend.position = NULL)

```

